export const Currencies = [
    { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-US' },
    { code: 'EUR', symbol: '€', name: 'Euro', locale: 'de-DE' },
    { code: 'GBP', symbol: '£', name: 'British Pound', locale: 'en-GB' },
    { code: 'JPY', symbol: '¥', name: 'Japanese Yen', locale: 'ja-JP' },
    { code: 'INR', symbol: '₹', name: 'Indian Rupee', locale: 'en-IN' },
    { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', locale: 'en-IN' },
    { code: 'CAD', symbol: '$', name: 'Canadian Dollar', locale: 'en-CA' },
    { code: 'AUD', symbol: '$', name: 'Australian Dollar', locale: 'en-AU' },
    { code: 'SGD', symbol: '$', name: 'Singapore Dollar', locale: 'en-SG' },
    { code: 'CHF', symbol: 'Fr', name: 'Swiss Franc', locale: 'de-CH' },
    { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', locale: 'zh-CN' },
    { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', locale: 'ar-AE' },
    { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal', locale: 'ar-SA' },
    { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', locale: 'en-PK' },
    { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee', locale: 'en-LK' },
    { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', locale: 'en-MY' },
    { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', locale: 'id-ID' },
    { code: 'THB', symbol: '฿', name: 'Thai Baht', locale: 'th-TH' },
    { code: 'NZD', symbol: '$', name: 'NZ Dollar', locale: 'en-NZ' },
    { code: 'HKD', symbol: '$', name: 'HK Dollar', locale: 'en-HK' },
    { code: 'ZAR', symbol: 'R', name: 'SA Rand', locale: 'en-ZA' },
    { code: 'RUB', symbol: '₽', name: 'Russian Ruble', locale: 'ru-RU' },
    { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', locale: 'pt-BR' },
    { code: 'MXN', symbol: '$', name: 'Mexican Peso', locale: 'es-MX' },
    { code: 'TRY', symbol: '₺', name: 'Turkish Lira', locale: 'tr-TR' },
    { code: 'KRW', symbol: '₩', name: 'South Korean Won', locale: 'ko-KR' },
    { code: 'PHP', symbol: '₱', name: 'Philippine Peso', locale: 'en-PH' },
    { code: 'VND', symbol: '₫', name: 'Vietnamese Dong', locale: 'vi-VN' },
    { code: 'ILS', symbol: '₪', name: 'Israeli Shekel', locale: 'he-IL' },
    { code: 'PLN', symbol: 'zł', name: 'Polish Zloty', locale: 'pl-PL' },
];

export default Currencies;
