import { AdUnits } from '@/src/constants/adUnits';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { formatCurrency } from './currencyFormatter';

/**
 * Shows an interstitial ad before PDF export if the user is not premium.
 */
export const showPdfInterstitial = (
    isPremium: boolean
): Promise<void> => {
    return new Promise((resolve) => {

        // Premium users or dev mode — skip ad
        if (__DEV__ || isPremium) {
            resolve();
            return;
        }

        try {
            const {
                InterstitialAd,
                AdEventType,
            } = require('react-native-google-mobile-ads');

            const interstitial = InterstitialAd.createForAdRequest(
                AdUnits.interstitial,
                { requestNonPersonalizedAdsOnly: true }
            );

            // Continue to PDF when ad closes
            interstitial.addAdEventListener(AdEventType.CLOSED, () => {
                resolve();
            });

            // If ad fails continue to PDF anyway
            interstitial.addAdEventListener(
                AdEventType.ERROR,
                () => resolve()
            );

            interstitial.addAdEventListener(AdEventType.LOADED, () => {
                interstitial.show();
            });

            interstitial.load();

            // Safety timeout 5s — always resolve
            setTimeout(resolve, 5000);
        } catch (e) {
            resolve();
        }
    });
};

/**
 * Generates a PDF for a loan summary and amortization table
 */
export const generateLoanPDF = async (loanDetails: any, schedule: any) => {
    const htmlContent = `
    <html>
      <head>
        <style>
          body { font-family: 'Helvetica', sans-serif; padding: 20px; color: #333; }
          .header { text-align: center; margin-bottom: 40px; }
          .summary-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
          .summary-table td { padding: 10px; border-bottom: 1px solid #eee; }
          .summary-label { font-weight: bold; width: 40%; }
          .summary-value { text-align: right; color: #00c853; font-weight: bold; }
          .amort-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          .amort-table th { background-color: #f5f5f5; padding: 10px; text-align: left; font-size: 12px; }
          .amort-table td { padding: 8px; border-bottom: 1px solid #f0f0f0; font-size: 11px; }
          h2 { color: #00c853; border-bottom: 2px solid #00c853; padding-bottom: 10px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Loan EMI Summary</h1>
          <p>Generated by Smart Loan Planner</p>
        </div>

        <h2>Loan Details</h2>
        <table class="summary-table">
          <tr>
            <td class="summary-label">Loan Amount</td>
            <td class="summary-value">${formatCurrency(loanDetails.principal)}</td>
          </tr>
          <tr>
            <td class="summary-label">Interest Rate</td>
            <td class="summary-value">${loanDetails.rate}% (Annual)</td>
          </tr>
          <tr>
            <td class="summary-label">Tenure</td>
            <td class="summary-value">${loanDetails.tenure} Months</td>
          </tr>
          <tr>
            <td class="summary-label">Monthly EMI</td>
            <td class="summary-value">${formatCurrency(loanDetails.emi)}</td>
          </tr>
          <tr>
            <td class="summary-label">Total Interest</td>
            <td class="summary-value">${formatCurrency(loanDetails.totalInterest)}</td>
          </tr>
          <tr>
            <td class="summary-label">Total Payment</td>
            <td class="summary-value">${formatCurrency(loanDetails.totalPayable)}</td>
          </tr>
        </table>

        <h2>Amortization Schedule</h2>
        <table class="amort-table">
          <thead>
            <tr>
              <th>Mo</th>
              <th>Opening Bal</th>
              <th>Principal</th>
              <th>Interest</th>
              <th>Closing Bal</th>
            </tr>
          </thead>
          <tbody>
            ${schedule.map((item: any) => `
              <tr>
                <td>${item.month}</td>
                <td>${formatCurrency(item.openingBalance)}</td>
                <td>${formatCurrency(item.principalPaid)}</td>
                <td>${formatCurrency(item.interestPaid)}</td>
                <td>${formatCurrency(item.closingBalance)}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </body>
    </html>
  `;

    try {
        const { uri } = await Print.printToFileAsync({ html: htmlContent });
        if (await Sharing.isAvailableAsync()) {
            await Sharing.shareAsync(uri);
        }
    } catch (error) {
        console.error('PDF Generation Error:', error);
    }
};
